info:
  title: STD23044 - TD1
  version: 1.0.0

servers:
  - url: https://localhost.STD23044.com

paths:
  /customers:
    get:
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customers'

components:
  schemas:
    Customers:
      type: object
      properties:
        name:
          type: string
        yearsOld:
          type: integer
