Info:
  nom: STD23044 - TD1
  version: 1.0.0

Server:
  - URL: https://localhost.STD23044.com

Path:
  /customers:
    get:
      response:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
              type: array
              items: '#/Components/schema/Customers'

  Components:
    schema:
      Customers:
        type: object
        properties:
          name:
            type: String
          age:
            type: Integer